server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Route API calls to correct services
    location /api/auth/ {
        proxy_pass http://auth-service:5001/;
    }

    location /api/academic/ {
        proxy_pass http://academic-service:8000/;
    }
}